---
- name: Process Dynatrace EDA event
  hosts: localhost

  tasks:
    - name: Get problem details
      register: r_problem
      ansible.builtin.uri:
        url: "{{ lookup('env', 'DYNATRACE_HOST') }}/api/v2/problems/{{ ansible_eda.event['problemId'] }}"
        method: GET
        headers:
          Authorization: "Api-Token {{ lookup('env', 'DYNATRACE_API_TOKEN') }}"

    - name: Get problem hosts affected
      register: r_hosts
      loop: "{{ r_problem.json | dt_problem_hosts }}"
      loop_control:
        loop_var: host_id
      ansible.builtin.uri:
        url: "{{ lookup('env', 'DYNATRACE_HOST') }}/api/v2/entities/{{ host_id }}"
        method: GET
        headers:
          Authorization: "Api-Token {{ lookup('env', 'DYNATRACE_API_TOKEN') }}"

    - name: Get EC2 instances affected
      register: r_ec2_instances
      loop: "{{ r_hosts.results | map(attribute='json') | list }}"
      loop_control:
        loop_var: host
      ansible.builtin.uri:
        url: "{{ lookup('env', 'DYNATRACE_HOST') }}/api/v2/entities/{{ host['fromRelationships']['runsOn'][0]['id'] }}"
        method: GET
        headers:
          Authorization: "Api-Token {{ lookup('env', 'DYNATRACE_API_TOKEN') }}"

    - name: Setup hosts for next play
      ansible.builtin.set_fact:
        problem_ec2_instances: "{{ r_ec2_instances.results | json_query('[].json.properties.publicHostName') }}"

    - name: Create incident
      register: r_incident
      servicenow.itsm.incident:
        state: new
        caller: admin
        short_description: "{{ ansible_eda.event['title'] }}"
        description: Ansible EDA generated event based on Dynatrace Problems API
        impact: low
        urgency: low
        other:
          comments: "[code]<h3>Event-Driven Ansible Payload</h3>[/code]{{ ansible_eda.event | to_nice_json | codify }}"

    - name: Add incident comments | instances affected
      servicenow.itsm.incident:
        sys_id: "{{ r_incident.record.sys_id }}"
        other:
          comments: "[code]<h3>Affected Instances</h3>[/code]{{ r_ec2_instances.results | json_query('[].json') | to_nice_json | codify }}"

    - name: Add hosts to problem_ec2_instances
      loop: "{{ r_ec2_instances.results | json_query('[].json.properties.publicHostName') }}"
      ansible.builtin.add_host:
        name: '{{ item }}'
        groups: problem_ec2_instances
        problem_sys_id: "{{ r_incident.record.sys_id }}"
        dt_problem_id: "{{ problem_id }}"

- name: Remediate Problem
  hosts: problem_ec2_instances
  gather_facts: true
  
  tasks:
    - name: "Add incident comments | {{ inventory_hostname }} facts"
      delegate_to: localhost
      servicenow.itsm.incident:
        sys_id: "{{ problem_sys_id }}"
        other:
          comments: "[code]<h3>{{ inventory_hostname }} Facts</h3>[/code]{{ ansible_facts | to_nice_json | codify }}"

    - name: Start httpd
      become: true
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Close incident
      delegate_to: localhost
      servicenow.itsm.incident:
        sys_id: "{{ problem_sys_id }}"
        state: closed
        close_code: "Solved (Permanently)"
        close_notes: "Dynatrace + Event-Driven Ansible auto-remediation successful"

    - name: Close Dynatrace problem
      delegate_to: localhost
      ansible.builtin.uri:
        url: "{{ lookup('env', 'DYNATRACE_HOST') }}/api/v2/problems/{{ dt_problem_id }}/close"
        method: POST
        headers:
          Authorization: "Api-Token {{ lookup('env', 'DYNATRACE_API_TOKEN') }}"
        body_format: json
        body:
          message: "Dynatrace + Event-Driven Ansible auto-remediation successful"
