---
- name: Refresh Red Hat Automation Hub Token
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Get an access token
      register: r_refresh_token
      no_log: true
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: refresh_token
          client_id: cloud-services
          refresh_token: "{{ generic_token }}"
