---
- name: Test Credential Lookup Plugin(s)
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Use the Azure Key Vault lookup plugin
      when: az_client_secret is defined
      environment:
        AZ_TENANT_ID: "{{ az_tenant_id }}"
        AZ_CLIENT_ID: "{{ az_client_id }}"
        AZ_CLIENT_SECRET: "{{ az_client_secret }}"
      ansible.builtin.set_fact:
        test_secret: "{{ lookup('azure.azcollection.azure_keyvault_secret', az_kv_secret_name, vault_url=az_vault_url) }}"
