---
- name: Test Credential Lookup Plugin(s)
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Use the Azure Key Vault lookup plugin
      when:
        - az_client_secret is defined
        - az_client_secret != ''
      vars:
        tenant: "{{ az_tenant_id }}"
        client: "{{ az_client_id }}"
        secret: "{{ az_client_secret }}"
        vault: "{{ az_vault_url }}"
      ansible.builtin.set_fact: # noqa yaml[line-length]
        test_secret: "{{ lookup('azure.azcollection.azure_keyvault_secret', az_kv_secret_name, vault_url=vault, client_id=client, secret=secret, tenant_id=tenant) }}"
