---
- name: Create managed disks
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/vars/disk_tags.yml"

  tasks:
    - name: Create resource groups
      loop:
        - dev-rg
        - prod-rg
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ item }}"
        location: southcentralus
        tags:
          createdBy: ansible
          environment: "{{ item.split('-')[0] }}"

    - name: Create disks
      loop: "{{ disk_tags | dict2items }}"
      loop_control:
        loop_var: disk
        label: "{{ disk.key }}"
      azure.azcollection.azure_rm_manageddisk:
        disk_size_gb: "{{ disk.value.disk_size_gb | default('4') | int }}"
        name: "{{ disk.key }}"
        resource_group: "{{ disk.value.environment }}-rg"
        tags: "{{ disk.value }}"
        state: present
        storage_account_type: "{{ disk.value.storage_account_type | default('Standard_LRS') }}"
