---
- name: Snapshot managed disks
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get facts for all managed disks
      register: r_disk_info
      azure.azcollection.azure_rm_manageddisk_info:

    - name: Snapshot disk
      loop: "{{ r_disk_info.ansible_info.azure_managed_disk }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        disk: "{{ item }}"
      ansible.builtin.include_tasks:
        file: tasks/create_snapshot.yml
