---
- name: Set snapshot date
  ansible.builtin.set_fact:
    az_disk_snapshot_date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

- name: Snapshot disk
  register: r_disk_snapshot
  azure.azcollection.azure_rm_snapshot:
    resource_group: "{{ disk.id.split('/')[4] }}"
    name: "{{ disk.name }}-{{ az_disk_snapshot_date }}"
    location: "{{ disk.location }}"
    creation_data:
      create_option: Copy
      source_id: "{{ disk.id }}"
    sku:
      name: "{{ disk.storage_account_type }}"
    tags:
      environment: "{{ disk.tags.environment | default('UNK') }}"
      retention: "{{ disk.tags.retention | default('30d') }}"
      source: "{{ disk.name }}"
      owner: "{{ disk.tags.owner }}"
      createdOn: "{{ az_disk_snapshot_date }}"
      createdBy: "ansible"

- name: Get ARM API token
  register: r_arm_login
  ansible.builtin.uri:
    url: "https://login.microsoftonline.com/{{ lookup('env', 'AZURE_TENANT') }}/oauth2/v2.0/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: client_credentials
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
      client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      scope: https://management.azure.com/.default

- name: Tag snapshot
  ansible.builtin.uri:
    url: "https://management.azure.com/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ r_disk_snapshot.id.split('/')[4] }}/providers/Microsoft.Compute/snapshots/{{ r_disk_snapshot.id.split('/')[-1] }}?api-version=2023-04-02"
    method: PATCH
    status_code: [200,202]
    headers:
      Authorization: "Bearer {{ r_arm_login.json.access_token }}"
    body_format: json
    body:
      tags:
        environment: "{{ disk.tags.environment | default('UNK') }}"
        retention: "{{ disk.tags.retention | default('30d') }}"
        source: "{{ disk.name }}"
        owner: "{{ disk.tags.owner }}"
        createdOn: "{{ az_disk_snapshot_date }}"
        createdBy: ansible
