---
- name: Add disk space to EC2 instance
  hosts: localhost
  gather_facts: false
  tags: expand_disk

  vars:
    ansible_python_interpreter: /usr/bin/python3

  environment:
    AWS_REGION: us-east-1

  tasks:
    - name: Gather information about a particular instance using ID
      register: r_instance_info
      amazon.aws.ec2_instance_info:
        filters:
          tag:Name: "{{ _host }}"
          instance-state-name: ["running"]

    - name: Get volume info
      register: r_vol_info
      amazon.aws.ec2_vol_info:
        filters:
          volume-id: "{{ r_instance_info['instances'][0]['block_device_mappings'][0]['ebs']['volume_id'] }}"

    - name: Resize volume
      register: r_vol
      notify: Restart ec2
      amazon.aws.ec2_vol:
        instance: "{{ r_instance_info['instances'][0]['instance_id'] }}"
        id: "{{ r_instance_info['instances'][0]['block_device_mappings'][0]['ebs']['volume_id'] }}"
        modify_volume: true
        volume_size: "{{ (r_vol_info['volumes'][0].size * 1.2) | round(0, 'ceil') | int }}"

  handlers:
    - name: Restart ec2
      amazon.aws.ec2_instance:
        instance_ids:
          - "{{ r_instance_info['instances'][0]['instance_id'] }}"
        state: restarted

- name: Expand the filesystem
  hosts: "{{ _host | default(omit) }}"
  gather_facts: false
  tags: expand_fs

  tasks:
    - name: Wait for system to become reachable over WinRM
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Resize drive to max available size
      community.windows.win_partition:
        drive_letter: C
        partition_size: -1
