- name: Snapshot ec2 volume
  hosts: aws_ec2
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Ensure boto3 is installed
      ansible.builtin.pip:
        name: boto3
        state: present

  tasks:
    - name: Stop ec2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ instance_id }}"
        state: stopped
        wait: true

    - name: Get EC2 instance volumes
      register: r_vol_info
      amazon.aws.ec2_vol_info:
        filters:
          attachment.instance-id: "{{ instance_id }}"

    - name: Detach volumes
      loop: "{{ r_vol_info.volumes }}"
      loop_control:
        loop_var: volume
        label: "{{ volume.id }}"
      amazon.aws.ec2_vol:
        id: "{{ volume.id }}"
        instance: None

    - name: Get snapshot
      register: r_snapshots
      amazon.aws.ec2_snapshot_info:
        filters:
          "tag:Name": "{{ inventory_hostname }}"

    - name: Create volumes from snapshots
      amazon.aws.ec2_vol:
        instance: "{{ instance_id }}"
        snapshot: "{{ r_snapshots.snapshots[0].snapshot_id }}"
        device_name: "/dev/sda1"

    # - name: Start ec2 instance
    #   amazon.aws.ec2_instance:
    #     instance_ids: "{{ instance_id }}"
    #     state: started
    #     wait: true
