- name: Snapshot ec2 volume
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Ensure boto3 is installed
      ansible.builtin.pip:
        name: boto3
        state: present

  tasks:
    - name: Stop ec2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ instance_id }}"
        state: stopped
        wait: true

    - name: Get EC2 instance volumes
      register: r_vol_info
      amazon.aws.ec2_vol_info:
        filters:
          attachment.instance-id: "{{ instance_id }}"

    - name: Snapshot volumes
      loop: "{{ r_vol_info.volumes }}"
      loop_control:
        loop_var: volume
        label: "{{ volume.id }}"
      amazon.aws.ec2_snapshot:
        volume_id: "{{ volume.id }}"
        description: "Snapshot taken by ansible on {{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: Start ec2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ instance_id }}"
        state: started
        wait: true
