---
- name: Populate Service Now CMDB with EC2 instances
  hosts: all
  gather_facts: true

  tasks:
    - name: Write facts # noqa risky-file-permissions run-once[task]
      run_once: true
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ hostvars | to_nice_json }}"
        dest: ec2.json

    - name: Register the newly-created VM instance
      delegate_to: localhost
      servicenow.itsm.configuration_item:
        name: "{{ tags['Name'] }}"
        sys_class_name: cmdb_ci_ec2_instance
        ip_address: "{{ public_ip_address }}"
        mac_address: "{{ ansible_default_ipv4['macaddress'] | default(ansible_interfaces[0]['macaddress']) }}"
        other:
          vm_inst_id: "{{ instance_id }}"
          fqdn: "{{ inventory_hostname }}"
          dns_domain: "{{ ansible_domain }}"
          guest_os_fullname: "{{ ansible_distribution }}{{ ansible_distribution_version }}"
          cpus: "{{ processor_vcpus | default(ansible_processor_vcpus) }}"
          memory: "{{ ansible_memtotal_mb }}"
          classification: "{{ instance_type }}"
          location: "{{ placement['availability_zone'] }}"
          justification: "{{ tags['purpose'] }}"
          short_description: "{{ tags['info'] }}"
